version: '3.4'

services:
    desafio.decompor.api:
        image: desafio-decompor-api:latest
        container_name: desafio.decompor.api
        build:
            context: ./back-end/src
            dockerfile: ./Desafio.Decompor.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=5000
            - ASPNETCORE_HTTPS_PORTS=5001
            - ASPNETCORE_URLS=http://*:5000
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
            - desafio-decompor-networks
        
    desafio.decompor.client:
        image: desafio-decompor-client:latest
        container_name: desafio.decompor.client
        build:
            context: ./front-end
            dockerfile: ./desafio.decompor.client/Dockerfile              
        ports:
            - "4200:4200"
        depends_on:
            - desafio.decompor.api
        networks:
            - desafio-decompor-networks
  
networks:
  desafio-decompor-networks:    
    driver: bridge