apiVersion: v1
kind: Service
metadata:
  name: decompor-api-svc
spec:
  selector:
    app: decompor-api
  type: ClusterIP
  ports:
  - name: decompor-api-svc
    port: 5000
    protocol: TCP
    targetPort: 8080
