apiVersion: v1
kind: Service
metadata:
  name: decompor-web-svc
spec:
  selector:
    app: decompor-web
  type: LoadBalancer
  ports:
  - name: decompor-web-svc
    port: 4200
    protocol: TCP
    targetPort: 4200    
    